site_name: Grupo 09 – PrediAluguel 
site_url: https://unb-sistemas-de-machine-learning.github.io/Grupo09-PrediAluguel/
repo_url: https://github.com/unb-Sistemas-de-Machine-learning/Grupo09-PrediAluguel

nav:
  - Equipe: index.md
  - Cronograma: 
    - Sprints: "Planejamento/cronograma.md"
  - Engenharia de Requisitos:
    - Elicitação:
      - Requisitos do Projeto: Elicitacao/requisitosProduto.md
      - Requisitos de Machine Learning: Elicitacao/requisitosML.md
      - Backlog: Elicitacao/backlog.md
      - Histórias de Usuário: Elicitacao/historias_de_usuario.md
    - Artefatos: "Design_thinking/design_thinking.md"
    - Mapeamento de Dados: "Design_thinking/mapeamento_dados.md"
    - História do Usuário: "Design_thinking/us.md"
  - Arquitetura:
    - Pipeline de Dados: "Arquitetura/pipeline_dados.md"

extra_css:
  - stylesheets/extra.css
theme:
  language: pt-BR
  name: material
  favicon: assets/logo_agente.png
  logo: assets/logo_agente.png
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme : default
      primary: blue
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Mudar para o modo escuro 

    - scheme: slate
      primary: blue
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mudar para o modo claro
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra:
  analytics:
    provider: google
    property: G-7QVWYC7EZJ